---
- name: Configure snapshots and backups 
  hosts: servers
  gather_facts: true 
  become: true 
  vars_files: 
    - ../variables/backups.yml
    - ../variables/identity.yml

  tasks: 
    - name: Install rsnapshot
      ansible.builtin.apt:
        name: rsnapshot
        update_cache: yes
        state: present
    - name: copy rsnapshot configuration to hosts 
      ansible.builtin.template: 
        src: ../templates/rsnapshot.j2
        dest: /etc/rsnapshot.conf
        owner: "{{ admin }}"
        group: "{{ admin }}"
        mode: '0644'
        backup: yes 
    - name: copy rsnapshot cron configuration to hosts 
      ansible.builtin.template: 
        src: ../templates/rsnapshot_cron.j2
        dest: /etc/cron.d/rsnapshot
        owner: root
        group: root  
        mode: '0644'
        backup: yes 
