---
- name: update servers core development tools 
  hosts: servers 
  remote_user: "{{ user }}"
  become: true
  vars_files: 
    - ../variables/identity.yml
    - ../variables/packages.yml

  tasks: 
  - name: ensure tools are at latest version 
    package: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop: "{{ core_development_tools }}"
