--- 
- name: Configuration and management for network file system (NFS)
  hosts: nfs_server
  become: true 
  vars_files: 
    - ../variables/identity.yml
    - ../variables/nfs.yml

  tasks: 
    - name: Update apt cache and install nfs-kernel-server
      ansible.builtin.apt:
        name: nfs-kernel-server
        update_cache: yes
        state: present
    - name: Create soft link source for backups 
      ansible.builtin.file: 
        path: /nfs
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Create soft link for backups 
      ansible.builtin.file: 
        src: "/mnt/sda/rsnapshot/{{ nfs_server_hostname }}"
        dest: /nfs/backups
        state: link
        owner: root
        group: root
        mode: '0755'
    - name: Template out server configuration 
      ansible.builtin.template:
        src: ../templates/nfs_server_exports.j2
        dest: /etc/exports
        owner: root 
        group: root 
        mode: '0644'
        backup: yes 
      notify: 
      - restart nfs 
    - name: Configure firewall 
      community.general.ufw: 
        rule: allow 
        src: "{{ item }}" 
        port: '{{ nfs_port }}'
      loop: "{{ nfs_client_ips }}"
  handlers: 
    - name: restart nfs
      ansible.builtin.service: 
        name: nfs-kernel-server 
        state: restarted 
