---
- name: Manages core system services. 
  hosts: servers 
  remote_user: "{{ admin }}"
  become: true
  vars_files: 
    - ../variables/identity.yml

  tasks: 
  - name: ensure ssh is active 
    ansible.builtin.service: 
      name: ssh 
      state: started 
